//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaClienteDTO", Namespace="http://tempuri.org/")]
    public partial class CuentaClienteDTO : object
    {
        
        private string NumeroCuentaField;
        
        private decimal SaldoField;
        
        private int IdClienteField;
        
        private string NombreClienteField;
        
        private string ApellidoClienteField;
        
        private string DisponibilidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroCuenta
        {
            get
            {
                return this.NumeroCuentaField;
            }
            set
            {
                this.NumeroCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApellidoCliente
        {
            get
            {
                return this.ApellidoClienteField;
            }
            set
            {
                this.ApellidoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Disponibilidad
        {
            get
            {
                return this.DisponibilidadField;
            }
            set
            {
                this.DisponibilidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://tempuri.org/")]
    public partial class Movimiento : object
    {
        
        private int IdMovimientoField;
        
        private string NumeroOperacionField;
        
        private string NumeroCuentaField;
        
        private int IdEmpleadoField;
        
        private string NombreEmpleadoField;
        
        private string TipoField;
        
        private decimal MontoField;
        
        private string FechaHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdMovimiento
        {
            get
            {
                return this.IdMovimientoField;
            }
            set
            {
                this.IdMovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NumeroOperacion
        {
            get
            {
                return this.NumeroOperacionField;
            }
            set
            {
                this.NumeroOperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroCuenta
        {
            get
            {
                return this.NumeroCuentaField;
            }
            set
            {
                this.NumeroCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdEmpleado
        {
            get
            {
                return this.IdEmpleadoField;
            }
            set
            {
                this.IdEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NombreEmpleado
        {
            get
            {
                return this.NombreEmpleadoField;
            }
            set
            {
                this.NombreEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EurekaBankWSControlador")]
    public interface EurekaBankWSControlador
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/AutenticarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AutenticarUsuarioResponse> AutenticarUsuarioAsync(ServiceReference1.AutenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/Depositar", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DepositarResponse> DepositarAsync(ServiceReference1.DepositarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/Retirar", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RetirarResponse> RetirarAsync(ServiceReference1.RetirarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/Transferir", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TransferirResponse> TransferirAsync(ServiceReference1.TransferirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/ListarCuentasPorSucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CuentaClienteDTO[]> ListarCuentasPorSucursalAsync(int sucursalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/ConsultarExtracto", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarExtractoResponse> ConsultarExtractoAsync(ServiceReference1.ConsultarExtractoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EurekaBankWSControlador/ConsultarCuentasPorCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentasPorClienteResponse> ConsultarCuentasPorClienteAsync(ServiceReference1.ConsultarCuentasPorClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AutenticarUsuarioRequestBody Body;
        
        public AutenticarUsuarioRequest()
        {
        }
        
        public AutenticarUsuarioRequest(ServiceReference1.AutenticarUsuarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarUsuarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public AutenticarUsuarioRequestBody()
        {
        }
        
        public AutenticarUsuarioRequestBody(string usuario, string clave)
        {
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AutenticarUsuarioResponseBody Body;
        
        public AutenticarUsuarioResponse()
        {
        }
        
        public AutenticarUsuarioResponse(ServiceReference1.AutenticarUsuarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarUsuarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutenticarUsuarioResult;
        
        public AutenticarUsuarioResponseBody()
        {
        }
        
        public AutenticarUsuarioResponseBody(string AutenticarUsuarioResult)
        {
            this.AutenticarUsuarioResult = AutenticarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Depositar", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DepositarRequestBody Body;
        
        public DepositarRequest()
        {
        }
        
        public DepositarRequest(ServiceReference1.DepositarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int empleadoId;
        
        public DepositarRequestBody()
        {
        }
        
        public DepositarRequestBody(string cuentaId, double monto, int empleadoId)
        {
            this.cuentaId = cuentaId;
            this.monto = monto;
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DepositarResponseBody Body;
        
        public DepositarResponse()
        {
        }
        
        public DepositarResponse(ServiceReference1.DepositarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DepositarResult;
        
        public DepositarResponseBody()
        {
        }
        
        public DepositarResponseBody(string DepositarResult)
        {
            this.DepositarResult = DepositarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Retirar", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RetirarRequestBody Body;
        
        public RetirarRequest()
        {
        }
        
        public RetirarRequest(ServiceReference1.RetirarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetirarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int empleadoId;
        
        public RetirarRequestBody()
        {
        }
        
        public RetirarRequestBody(string cuentaId, double monto, int empleadoId)
        {
            this.cuentaId = cuentaId;
            this.monto = monto;
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetirarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RetirarResponseBody Body;
        
        public RetirarResponse()
        {
        }
        
        public RetirarResponse(ServiceReference1.RetirarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetirarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetirarResult;
        
        public RetirarResponseBody()
        {
        }
        
        public RetirarResponseBody(string RetirarResult)
        {
            this.RetirarResult = RetirarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transferir", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TransferirRequestBody Body;
        
        public TransferirRequest()
        {
        }
        
        public TransferirRequest(ServiceReference1.TransferirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaOrigenId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuentaDestinoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int empleadoId;
        
        public TransferirRequestBody()
        {
        }
        
        public TransferirRequestBody(string cuentaOrigenId, string cuentaDestinoId, double monto, int empleadoId)
        {
            this.cuentaOrigenId = cuentaOrigenId;
            this.cuentaDestinoId = cuentaDestinoId;
            this.monto = monto;
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TransferirResponseBody Body;
        
        public TransferirResponse()
        {
        }
        
        public TransferirResponse(ServiceReference1.TransferirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TransferirResult;
        
        public TransferirResponseBody()
        {
        }
        
        public TransferirResponseBody(string TransferirResult)
        {
            this.TransferirResult = TransferirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarExtractoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarExtracto", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarExtractoRequestBody Body;
        
        public ConsultarExtractoRequest()
        {
        }
        
        public ConsultarExtractoRequest(ServiceReference1.ConsultarExtractoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarExtractoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaId;
        
        public ConsultarExtractoRequestBody()
        {
        }
        
        public ConsultarExtractoRequestBody(string cuentaId)
        {
            this.cuentaId = cuentaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarExtractoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarExtractoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarExtractoResponseBody Body;
        
        public ConsultarExtractoResponse()
        {
        }
        
        public ConsultarExtractoResponse(ServiceReference1.ConsultarExtractoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarExtractoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ServiceReference1.Movimiento[] ConsultarExtractoResult;
        
        public ConsultarExtractoResponseBody()
        {
        }
        
        public ConsultarExtractoResponseBody(ServiceReference1.Movimiento[] ConsultarExtractoResult)
        {
            this.ConsultarExtractoResult = ConsultarExtractoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCuentasPorClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCuentasPorCliente", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarCuentasPorClienteRequestBody Body;
        
        public ConsultarCuentasPorClienteRequest()
        {
        }
        
        public ConsultarCuentasPorClienteRequest(ServiceReference1.ConsultarCuentasPorClienteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCuentasPorClienteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public ConsultarCuentasPorClienteRequestBody()
        {
        }
        
        public ConsultarCuentasPorClienteRequestBody(string dni)
        {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCuentasPorClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCuentasPorClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarCuentasPorClienteResponseBody Body;
        
        public ConsultarCuentasPorClienteResponse()
        {
        }
        
        public ConsultarCuentasPorClienteResponse(ServiceReference1.ConsultarCuentasPorClienteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCuentasPorClienteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.CuentaClienteDTO ConsultarCuentasPorClienteResult;
        
        public ConsultarCuentasPorClienteResponseBody()
        {
        }
        
        public ConsultarCuentasPorClienteResponseBody(ServiceReference1.CuentaClienteDTO ConsultarCuentasPorClienteResult)
        {
            this.ConsultarCuentasPorClienteResult = ConsultarCuentasPorClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface EurekaBankWSControladorChannel : ServiceReference1.EurekaBankWSControlador, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EurekaBankWSControladorClient : System.ServiceModel.ClientBase<ServiceReference1.EurekaBankWSControlador>, ServiceReference1.EurekaBankWSControlador
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EurekaBankWSControladorClient() : 
                base(EurekaBankWSControladorClient.GetDefaultBinding(), EurekaBankWSControladorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_EurekaBankWSControlador_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EurekaBankWSControladorClient(EndpointConfiguration endpointConfiguration) : 
                base(EurekaBankWSControladorClient.GetBindingForEndpoint(endpointConfiguration), EurekaBankWSControladorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EurekaBankWSControladorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EurekaBankWSControladorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EurekaBankWSControladorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EurekaBankWSControladorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EurekaBankWSControladorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AutenticarUsuarioResponse> ServiceReference1.EurekaBankWSControlador.AutenticarUsuarioAsync(ServiceReference1.AutenticarUsuarioRequest request)
        {
            return base.Channel.AutenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AutenticarUsuarioResponse> AutenticarUsuarioAsync(string usuario, string clave)
        {
            ServiceReference1.AutenticarUsuarioRequest inValue = new ServiceReference1.AutenticarUsuarioRequest();
            inValue.Body = new ServiceReference1.AutenticarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).AutenticarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DepositarResponse> ServiceReference1.EurekaBankWSControlador.DepositarAsync(ServiceReference1.DepositarRequest request)
        {
            return base.Channel.DepositarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DepositarResponse> DepositarAsync(string cuentaId, double monto, int empleadoId)
        {
            ServiceReference1.DepositarRequest inValue = new ServiceReference1.DepositarRequest();
            inValue.Body = new ServiceReference1.DepositarRequestBody();
            inValue.Body.cuentaId = cuentaId;
            inValue.Body.monto = monto;
            inValue.Body.empleadoId = empleadoId;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).DepositarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RetirarResponse> ServiceReference1.EurekaBankWSControlador.RetirarAsync(ServiceReference1.RetirarRequest request)
        {
            return base.Channel.RetirarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RetirarResponse> RetirarAsync(string cuentaId, double monto, int empleadoId)
        {
            ServiceReference1.RetirarRequest inValue = new ServiceReference1.RetirarRequest();
            inValue.Body = new ServiceReference1.RetirarRequestBody();
            inValue.Body.cuentaId = cuentaId;
            inValue.Body.monto = monto;
            inValue.Body.empleadoId = empleadoId;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).RetirarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TransferirResponse> ServiceReference1.EurekaBankWSControlador.TransferirAsync(ServiceReference1.TransferirRequest request)
        {
            return base.Channel.TransferirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TransferirResponse> TransferirAsync(string cuentaOrigenId, string cuentaDestinoId, double monto, int empleadoId)
        {
            ServiceReference1.TransferirRequest inValue = new ServiceReference1.TransferirRequest();
            inValue.Body = new ServiceReference1.TransferirRequestBody();
            inValue.Body.cuentaOrigenId = cuentaOrigenId;
            inValue.Body.cuentaDestinoId = cuentaDestinoId;
            inValue.Body.monto = monto;
            inValue.Body.empleadoId = empleadoId;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).TransferirAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CuentaClienteDTO[]> ListarCuentasPorSucursalAsync(int sucursalId)
        {
            return base.Channel.ListarCuentasPorSucursalAsync(sucursalId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarExtractoResponse> ServiceReference1.EurekaBankWSControlador.ConsultarExtractoAsync(ServiceReference1.ConsultarExtractoRequest request)
        {
            return base.Channel.ConsultarExtractoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConsultarExtractoResponse> ConsultarExtractoAsync(string cuentaId)
        {
            ServiceReference1.ConsultarExtractoRequest inValue = new ServiceReference1.ConsultarExtractoRequest();
            inValue.Body = new ServiceReference1.ConsultarExtractoRequestBody();
            inValue.Body.cuentaId = cuentaId;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).ConsultarExtractoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentasPorClienteResponse> ServiceReference1.EurekaBankWSControlador.ConsultarCuentasPorClienteAsync(ServiceReference1.ConsultarCuentasPorClienteRequest request)
        {
            return base.Channel.ConsultarCuentasPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentasPorClienteResponse> ConsultarCuentasPorClienteAsync(string dni)
        {
            ServiceReference1.ConsultarCuentasPorClienteRequest inValue = new ServiceReference1.ConsultarCuentasPorClienteRequest();
            inValue.Body = new ServiceReference1.ConsultarCuentasPorClienteRequestBody();
            inValue.Body.dni = dni;
            return ((ServiceReference1.EurekaBankWSControlador)(this)).ConsultarCuentasPorClienteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_EurekaBankWSControlador_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_EurekaBankWSControlador_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.101:8080/EurekaBankWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EurekaBankWSControladorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_EurekaBankWSControlador_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EurekaBankWSControladorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_EurekaBankWSControlador_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_EurekaBankWSControlador_soap,
        }
    }
}
